SOURCES=Song.cpp Database.cpp lib/cmdapp/cpp/TaskBase.cpp \
			  lib/cmdapp/cpp/Task.cpp lib/cmdapp/cpp/Cmd.cpp \
			  $(foreach TASK,$(wildcard tasks/cpp/*.cpp), $(TASK)) \
			  SongBookApp.cpp main.cpp
OUTPUT_FILE=songbook.out
H_FILES=lib/json/json.hpp lib/argparse/argparse.hpp

# shall be overriden in CLI 
TASK_NAME?=
# Default html open
BROWSER=xdg-open

.PHONY: all
all: gen_tests compile link run

.PHONY: compile-lib
compile-lib:
	@g++ -c $(H_FILES)

.PHONY: create_task
create_task:
	$(if $(TASK_NAME),,$(error TASK_NAME var empty, cannot create task!))
	@touch tasks/cpp/$(TASK_NAME).cpp
	@echo '#include <string>' >> tasks/cpp/$(TASK_NAME).cpp
	@echo '#include <iostream>' >> tasks/cpp/$(TASK_NAME).cpp
	@echo '#include <iomanip>' >> tasks/cpp/$(TASK_NAME).cpp
	@echo '#include "../h/$(TASK_NAME).h"' >> tasks/cpp/$(TASK_NAME).cpp
	@echo '#include "../../SongBookApp.h"' >> tasks/cpp/$(TASK_NAME).cpp
	@echo '' >> tasks/cpp/$(TASK_NAME).cpp
	@echo "int $(TASK_NAME)::Start()" >> tasks/cpp/$(TASK_NAME).cpp
	@echo '{' >> tasks/cpp/$(TASK_NAME).cpp
	@echo  '  std::cout << "TO BE IMPLEMENTED" << std::endl;'>> tasks/cpp/$(TASK_NAME).cpp
	@echo  "  return 1;" >> tasks/cpp/$(TASK_NAME).cpp
	@echo '}' >> tasks/cpp/$(TASK_NAME).cpp   
	@touch tasks/h/$(TASK_NAME).h
	@echo '#include <string>'    >> tasks/h/$(TASK_NAME).h
	@echo '#include "../../lib/cmdapp/cmdapp.h"'    >> tasks/h/$(TASK_NAME).h
	@echo "" >> tasks/h/$(TASK_NAME).h
	@echo 'class SongBookApp;'     >> tasks/h/$(TASK_NAME).h
	@echo "" >> tasks/h/$(TASK_NAME).h
	@echo "class $(TASK_NAME) : public Task<SongBookApp>"    >> tasks/h/$(TASK_NAME).h
	@echo "{"    >> tasks/h/$(TASK_NAME).h
	@echo "public:"    >> tasks/h/$(TASK_NAME).h
	@echo "  $(TASK_NAME)(std::string cmd, SongBookApp* parent) "    >> tasks/h/$(TASK_NAME).h
	@echo "    : Task<SongBookApp>(cmd, parent) {};"    >> tasks/h/$(TASK_NAME).h
	@echo ""    >> tasks/h/$(TASK_NAME).h
	@echo "int Start() override;"    >> tasks/h/$(TASK_NAME).h
	@echo "" >> tasks/h/$(TASK_NAME).h
	@echo '};'    >> tasks/h/$(TASK_NAME).h

gen_tests:
	@echo "// Autogenerated by Makefile ..." > tasks/tasks.h
	@echo "" >> tasks/tasks.h
	@for TASK in $(notdir $(wildcard tasks/h/*.h)); do echo "#include \"h/$$TASK\""; done >> tasks/tasks.h

# TODO
.PHONY: lib
lib:
	g++ -shared $(H_FILES) Song.cpp Database.cpp -o Database.so

.PHONY: build
build: compile-lib compile link

# TODO remove
.PHONY: debug
debug: compile-with-debug link
	gdb ./$(OUTPUT_FILE)

.PHONY: run
run:
	@./$(OUTPUT_FILE)

# TODO remove
.PHONY: compile-with-debug
compile-with-debug:
	g++ -g -c $(H_FILES) $(SOURCES)

compile:
	@g++ -c $(SOURCES)

.PHONY: clean
clean:
	@rm *.o
	@rm ./$(OUTPUT_FILE)

.PHONY: doxygen
doxygen:
	$(if $(wildcard docs),,$(shell mkdir docs))
	@doxygen doxygen.conf

.PHONY: docs
docs:
	@$(BROWSER) docs/html/index.html

link:
	@g++ $(foreach file, $(SOURCES), $(notdir $(basename $(file)).o)) -o $(OUTPUT_FILE)
	rm *.o
