// Autogenerated by Makefile ...

#include "h/AddTask.h"
#include "h/BackupTask.h"
#include "h/ExitTask.h"
#include "h/FindTask.h"
#include "h/GatherTask.h"
#include "h/HelpTask.h"
#include "h/LatexTask.h"
#include "h/ListTask.h"
#include "h/ModifyTask.h"
#include "h/RemoveTask.h"
#include "h/SortTask.h"
#include "h/TestTask.h"
