#include <string>
#include <iostream>
#include <cwchar>
#include <algorithm>
#include "Window.h"

Window::Window(std::string name, int width, int height, int pos_x, int pos_y)
{   
    this->name = name;
    this->width = width;
    this->height = height;
    this->pos_x = pos_x;
    this->pos_y = pos_y;
}

std::wstring Window::utf8_to_wstring(const std::string& s)
{
    std::wstring ws;
    ws.resize(mbstowcs(nullptr, s.c_str(), 0));
    mbstowcs(ws.data(), s.c_str(), ws.size());
    return ws;
}

// generated by ChatGPT
void Window::Print(const std::wstring& txt, bool newline)
{
    int max_y, max_x;
    getmaxyx(win, max_y, max_x);

    const int left   = 1;
    const int right  = max_x - 2;
    const int top    = 1;
    const int bottom = max_y - 2;

    scrollok(win, TRUE);

    int y, x;
    getyx(win, y, x);

    if (y < top) y = top;
    if (x < left) x = left;

    wmove(win, y, x);

    for (wchar_t ch : txt)
    {
        getyx(win, y, x);

        // --- Handle newline ---
        if (ch == L'\n')
        {
            x = left;
            y++;
        }
        // --- Handle carriage return ---
        else if (ch == L'\r')
        {
            x = left;
        }
        // --- Handle tab (4 spaces) ---
        else if (ch == L'\t')
        {
            int tabsize = 4;
            int spaces = tabsize - ((x - left) % tabsize);

            for (int i = 0; i < spaces; ++i)
            {
                if (x > right)
                {
                    x = left;
                    y++;
                }

                mvwaddch(win, y, x++, L' ');
            }
        }
        // --- Normal character ---
        else
        {
            int w = wcwidth(ch);
            if (w < 0) w = 1; // non-printable fallback

            if (x + w - 1 > right)
            {
                x = left;
                y++;
            }

            mvwaddnwstr(win, y, x, &ch, 1);
            x += w;
        }

        // --- Handle scrolling ---
        if (y > bottom)
        {
            wscrl(win, 1);
            y = bottom;
        }

        wmove(win, y, x);
    }

    if (newline)
    {
        getyx(win, y, x);
        x = left;
        y++;

        if (y > bottom)
        {
            wscrl(win, 1);
            y = bottom;
        }

        wmove(win, y, x);
    }

    box(win, 0, 0);
    wrefresh(win);
}

void Window::Print(const std::string& txt, bool newline)
{
    // Convert UTF-8 → wide string
    std::wstring wtxt = utf8_to_wstring(txt);

    Print(wtxt, newline);
}

std::string Window::GetString(int max_length)
{   
    if (max_length > 100 || max_length < 1)  {
        std::cerr << "max_length cannot exceed 100 for memory safety reason!" << std::endl;
        return "";
    }

    echo();

    char input[100];

    wgetnstr(this->win, input, 99);   // Read string
    noecho();

    return std::string(input);
}


void Window::Init()
{
    this->win = newwin(this->height, this->width, this->pos_y, this->pos_x);
    box(this->win, 0, 0);
}

void Window::Refresh()
{
    wrefresh(this->win);
}

void Window::Print(const std::string& txt, short background_color, short foreground_color, bool bold)
{   
    init_pair(1, background_color, foreground_color);
    wattron(this->win, COLOR_PAIR(1));

    if (bold)  {
        wattron(win, A_BOLD);
    }

    Print(txt);

    if (bold)  {
        wattroff(win, A_BOLD);
    }
}

void Window::Clear()
{
    wclear(this->win);
}

void Window::Delete()
{
    endwin();
}